# Generated by Django 5.1.5 on 2025-06-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_delete_admin_remove_cours_etudiants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_professeur', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='mot_de_passe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom_etudiant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.professeur'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
